namespace Bridge.Api.Domain;

public sealed class AppUser { public Guid Id { get; set; } = Guid.NewGuid(); public string DisplayName { get; set; } = "Learner"; public bool IsAnonymous { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public UserProfile? Profile { get; set; } public List<PracticeSession> Sessions { get; set; } = []; }
public sealed class UserProfile { public Guid UserId { get; set; } public string? CountryOfOrigin { get; set; } public string UsExperience { get; set; } = ""; public int BaselineConfidence { get; set; } public int CurrentConfidence { get; set; } public string HardestActorType { get; set; } = "friend"; public int ClassroomComfort { get; set; } public int DisagreementComfort { get; set; } public int SmallTalkComfort { get; set; } public string AssessmentVersion { get; set; } = "v1"; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public AppUser User { get; set; } = null!; }
public sealed class Actor { public string Id { get; set; } = ""; public string ActorType { get; set; } = ""; public string Name { get; set; } = ""; public string Role { get; set; } = ""; public string Personality { get; set; } = ""; public string CommunicationStyle { get; set; } = ""; public bool IsActive { get; set; } = true; public List<Scenario> Scenarios { get; set; } = []; }
public sealed class Scenario { public string Id { get; set; } = ""; public string ActorId { get; set; } = ""; public string Title { get; set; } = ""; public string Description { get; set; } = ""; public string Goal { get; set; } = ""; public string Difficulty { get; set; } = "medium"; public string OpeningMessage { get; set; } = ""; public string CultureContext { get; set; } = ""; public string PromptInstructions { get; set; } = ""; public bool IsActive { get; set; } = true; public Actor Actor { get; set; } = null!; }
public sealed class PracticeSession { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string ActorId { get; set; } = ""; public string ScenarioId { get; set; } = ""; public int DirectnessLevel { get; set; } = 3; public string Status { get; set; } = "active"; public string PromptVersion { get; set; } = "roleplay-v1"; public DateTimeOffset StartedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? CompletedAt { get; set; } public AppUser User { get; set; } = null!; public Actor Actor { get; set; } = null!; public Scenario Scenario { get; set; } = null!; public List<ChatMessage> Messages { get; set; } = []; public SessionEvaluation? Evaluation { get; set; } public List<QuizAttempt> QuizAttempts { get; set; } = []; }
public sealed class ChatMessage { public Guid Id { get; set; } = Guid.NewGuid(); public Guid SessionId { get; set; } public Guid? ClientMessageId { get; set; } public string Role { get; set; } = ""; public string Content { get; set; } = ""; public int SequenceNumber { get; set; } public int? GoalProgress { get; set; } public string? CultureNoteType { get; set; } public string? CultureNote { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public PracticeSession Session { get; set; } = null!; }
public sealed class SessionEvaluation { public Guid Id { get; set; } = Guid.NewGuid(); public Guid SessionId { get; set; } public int OverallScore { get; set; } public int ClarityScore { get; set; } public int DirectnessScore { get; set; } public int WarmthScore { get; set; } public int EngagementScore { get; set; } public int GoalCompletionScore { get; set; } public string StrengthsJson { get; set; } = "[]"; public string ImprovementsJson { get; set; } = "[]"; public string CultureGapJson { get; set; } = "{}"; public string Summary { get; set; } = ""; public string ModelName { get; set; } = ""; public string PromptVersion { get; set; } = "evaluation-v1"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public PracticeSession Session { get; set; } = null!; }
public sealed class QuizAttempt { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public Guid SessionId { get; set; } public string QuestionsJson { get; set; } = "[]"; public string AnswersJson { get; set; } = "[]"; public int Score { get; set; } public int MaxScore { get; set; } public int ConfidenceBefore { get; set; } public int ConfidenceAfter { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public AppUser User { get; set; } = null!; public PracticeSession Session { get; set; } = null!; }
